spring:
  application:
    name: "pcr-habilitations"
  datasource:
    url: jdbc:h2:mem:examendb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
    schema: schema.sql
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
    path: /h2-console
